=== Overview

This overview will introduce the various components wrapped into the Cloudera Ansible Foundry, and Terminology used throughout this Documentation.

==== Cloudera-Deploy Components

.cloudera-deploy
Playbooks, User, and Definition handling for both new and advanced users.  +
Standard Entry point for most users, most of the time.

.cldr-runner
A Container image as a common Runner with all dependencies suitable for use locally, with Ansible Tower, against an IDE, or various other circumstances

.cdpy
A Python client for the CDP Control Plane, both Public and Private

.Cloudera Ansible Collections
** cloudera.cloud; un-opinionated modules for the CDP Control Plane in Public or Private Cloud
** cloudera.exe; highly opinionated roles for most task sequences
** cloudera.cluster; Deploy & Configure Clusters via Cloudera Manager
** cloudera.runtime; modules and roles for services within CDP

.Deployment Definitions
Example Definitions for use with Cloudera-Deploy, presently bundled https://github.com/cloudera-labs/cloudera-deploy/tree/main/examples[here]

We plan on publishing more examples soon.

==== Terminology
Some terms used herein have specific meaning, and are usually Capitalised in the document to indicate they are being used in that specific context.

.Playbooks
Are referring to Ansible Playbooks, and are generally the main entrypoint into Runs

.Run
Some execution of a Playbook

NOTE: When using the Runner, Runs are automatically logged back to the user profile and use a collection of default settings known to be good in most situations

.Runner
Refers to https://github.com/cloudera-labs/cldr-runner[cldr-runner], a common Execution Environment. This is built from a Dockerfile maintained by the Ansible community, to which the various dependencies for CDP and Hybrid Cloud Architectures are added.

.Definition
A directory containing files expected by the Playbooks which describe the Deployment. The Definition directory also doubles as a working directory for artefacts produced in the Run. The files and details around composability will be explained later.

.Deployment Definitions
Refers to one or more of these Definition directories that may be provided by default with Cloudera-Deploy, created by the user, or some other process

.Tags
Tags is an overloaded term, and may be referring to:

* 'Ansible Tags', which control what actions will be executed within the Run based on the Definition. At the simplest level this is things like ‘deploy’ or ‘teardown’ but can provide a great deal of control with sophisticated use
* 'Tags' applied to cloud infrastructure, which is strongly recommended for all users

.Profile
Profile is an overloaded term and may refer to any of the following depending on context:

* A profile specifically for Cloudera-Deploy which provides the lowest precedence of user defaults for things like Passwords. Usually found in `~/.config/cloudera-deploy/profiles` on Linux machines
* A profile used with some external API, such as AWS, Azure, GCP or CDP, which usually specifies things like credentials, endpoints, regions, etc. Usually found in `~/.aws` or similar on Linux machines
* Your local User Profile on your machine. When using the Runner, it mounts key User Profile directories such as your .ssh and .config folders in provide you access to those files with the various tools. Usually `/home/<user>` on Linux machines.


include::architecture.adoc[]

include::definitions.adoc[]

include::cdp_public.adoc[]

include::cdp_base.adoc[]

include::dynamic_inventory.adoc[]

include::developers.adoc[]


